# Generated by Django 4.0.1 on 2022-01-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, unique=True, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(auto_now=True, verbose_name='Date de mise en ligne')),
                ('date_up', models.DateField(auto_now_add=True, verbose_name='Date de mise à jours')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblio.data')),
                ('file', models.FileField(upload_to='Cours/%d-%M-%Y', verbose_name='Fichier (Vidéo)')),
            ],
            bases=('biblio.data',),
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblio.data')),
                ('file', models.FileField(upload_to='Ebook/%d-%M-%Y', verbose_name='Fichier (PDF, EBOOK)')),
            ],
            bases=('biblio.data',),
        ),
    ]
