# Generated by Django 4.0.1 on 2022-01-10 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_alter_data_keydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='classe',
            field=models.CharField(choices=[('Seconde A', 'Seconde A'), ('Seconde S', 'Seconde S'), ('Permiere A', 'Premiere A'), ('Permiere S', 'Premiere S'), ('Terminale A', 'Terminale A'), ('Terminale S', 'Terminale S')], default=' ', max_length=100, verbose_name='Choisissez une classe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='keydata',
            field=models.UUIDField(default=uuid.UUID('ec3a0507-09d7-4831-9f98-947869d9cd1c')),
        ),
    ]
