# Generated by Django 4.0.1 on 2022-01-11 03:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_data_classe_alter_data_keydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='keydata',
            field=models.UUIDField(default=uuid.UUID('ff4b92fd-fad8-4840-95cf-3e161a6d0313')),
        ),
    ]
